### ISSUE TITLE
Tessendorf's simulating ocean wave equation 19

### ISSUE THREAD

**Issue by lihas** [JiashuoLi/OceanSurface#1]
I am trying to implement Tessendorf's simulating ocean water paper.
(http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.161.9102&rep=rep1&type=pdf)
I want to create simplest implementation, without surface normals, etc.
I am unable to understand what summation (sigma) in equation 19 means.
What are the values of k over which we are summing?
Is the summation variable k related to the vector K (which consists of Kx, and Kz)?
I want to implement the maths myself to the maximum extent possible, looking at your code therefore would be my last resort.
![image](https://user-images.githubusercontent.com/1687568/55512399-abd24e80-5680-11e9-992c-1fbec6fe9353.png)

**Comment by lihas** [comment]
> I am trying to implement Tessendorf's simulating ocean water paper.
> (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.161.9102&rep=rep1&type=pdf)
> I want to create simplest implementation, without surface normals, etc.
> I am unable to understand what summation (sigma) in equation 19 means.
> What are the values of k over which we are summing?
> Is the summation variable k related to the vector K (which consists of Kx, and Kz)?
> I want to implement the maths myself to the maximum extent possible, looking at your code therefore would be my last resort.
> ![image](https://user-images.githubusercontent.com/1687568/55512399-abd24e80-5680-11e9-992c-1fbec6fe9353.png)

Also, once you get h(X,t), which is essentially a complex quantity, how do you map it to wave height? Do you just ignore the complex part?

**Comment by jiasli** [comment]
Hi @lihas , I did this project several years ago in university and has nearly forgotten the algorithm. Based on my memory, yes, k is all vectors, consisting of kx and kz. The big Sigma is computed using FFT, which transforms complex quantities to wave heights. The code is well documented. Hope it helps.
